Task 1:


Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)

In [17]:
import pandas as pd
import numpy as np
import random

alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

data = {

    'Goals': np.random.randint(0, 100, size=4),
    'Assists': np.random.randint(0, 50, size=4),
    'Shots on Target': np.random.randint(10, 100, size=4),
    'Pass Completion': np.random.uniform(50.0, 95.0, size=4),
    'Club': [random.choice(['Club A', 'Club B', 'Club C']) for _ in range(4)]
}

df = pd.DataFrame(data)
print(df)

   Goals  Assists  Shots on Target  Pass Completion    Club
0     34       15               44        62.190352  Club A
1     82        2               48        88.886800  Club C
2     25       11               15        78.187411  Club B
3     67       36               79        69.201099  Club B

Task 2:

Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4

In [18]:
df.rename(columns={'Goals':'Random value 1', 'Assists':'Random value 2', 'Shots on Target':'Random value 3', 'Pass Completion':'Random value 4', 'Club':'Random value 5'}, inplace=True)
df

,Random value 1,Random value 2,Random value 3,Random value 4,Random value 5
0,34,15,44,62.190352,Club A
1,82,2,48,88.886800,Club C
2,25,11,15,78.187411,Club B
3,67,36,79,69.201099,Club B

Task 3:

Find the descriptive statistics of the 'df' dataframe

In [19]:
df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean        52.000000       16.000000       46.500000       74.616415
std         26.944387       14.399074       26.185238       11.548861
min         25.000000        2.000000       15.000000       62.190352
25%         31.750000        8.750000       36.750000       67.448412
50%         50.500000       13.000000       46.000000       73.694255
75%         70.750000       20.250000       55.750000       80.862258
max         82.000000       36.000000       79.000000       88.886800

Task 4:

Check for the null values in 'df' and find the data type of the columns

In [20]:
df.isnull().any()

Random value 1    False
Random value 2    False
Random value 3    False
Random value 4    False
Random value 5    False
dtype: bool

In [21]:
data = df.dtypes
data

Random value 1      int64
Random value 2      int64
Random value 3      int64
Random value 4    float64
Random value 5     object
dtype: object

Task 5:

Display the 'Random value 2' & 'Random value 3' columns with location method and index location method

In [22]:
df.loc[:,['Random value 2','Random value 3']]

   Random value 2  Random value 3
0              15              44
1               2              48
2              11              15
3              36              79

In [23]:
df.iloc[:,[1,2]]

   Random value 2  Random value 3
0              15              44
1               2              48
2              11              15
3              36              79